### PR TITLE
Clean up old Python fixtures

### PR DESCRIPTION
**Pull request by dralley**
Pulp 2 and 3 tests are both using the newer, more comprehensive fixtures, and the Pulp-2-Tests repo doesn't contain any references to the older ones. They aren't needed any more.

### CODE REVIEW

**Comment by dralley** [comment]
Missed a spot in the readme -- fixed now.

**Comment by kersommoura** [comment]
See: https://github.com/PulpQE/pulp-smash/commit/ee616b205993f3dc7402eedfb5b3975e32469283

**Comment by kersommoura** [comment]
@dralley, please, can you remove the following lines from the Makefile.

```make
141 fixtures/python \
142 fixtures/python-pulp \
```

**Comment by dralley** [comment]
@kersommoura fixed

**Comment by kersommoura** [comment]
Thanks.

**Pull request merged**
