### PR TITLE
Add json api to python fixture

### PR DESCRIPTION
**Pull request by asmacdo**
Mimics the json api of PyPI. The actual structure and files are produced
by a pulp publish so this effectively tests a pulp to pulp sync as well.

### CODE REVIEW

**Comment by Ichimonji10** [comment]
PyPi provides this JSON metadata as a pair of identical files, one ending in `.json` and the other in `.html`. See:

* https://pypi.python.org/pypi/shelf-reader/json/index.json
* https://pypi.python.org/pypi/pulp-smash/json/index.html

If the intent is to mimic PyPi, does it make more sense to create an `index.json` file, and create a symlink pointing to it named `index.html`?

On a nit-pickier note, `json_reformat` is good at making files look nice.

Here's a code summary of my suggestions:

```bash
#!/usr/bin/env bash
set -euo pipefail

json_reformat \
    < python/assets/pypi/shelf-reader/json/index.html \
    > python/assets/pypi/shelf-reader/json/index.json
rm python/assets/pypi/shelf-reader/json/index.html
ln -s  ./index.json python/assets/pypi/shelf-reader/json/index.html
```

**Comment by asmacdo** [comment]
Unfortunately, the symlink didn't work the way I expected with default `python -m http.server`, so I just created a second file.

**Comment by Ichimonji10** [comment]
This change looks sane. I also make sure to generate the updated fixtures, host them with `python3 -m http.server`, update the Pulp Smash constants file to point to the served files, and run `python -m unittest discover pulp_smash.tests.python`. All tests passed. Merging. Thank you, @asmacdo!

**Comment by elyezer** [comment]
:+1:

**Pull request merged**
