### PR TITLE
Update to use newly published Pulp metatdata

### PR DESCRIPTION
**Pull request by asmacdo**
Also fixes a sync problem.

### CODE REVIEW

**Comment by Ichimonji10** [comment]
The `path` is the only thing that's changed, right? Everything appears to be a semantic no-op, like rearranging keys in a dict or adding additional indentation.

**Comment by asmacdo** [comment]
@Ichimonji10 correct.

**Comment by Ichimonji10** [comment]
Tested against Pulp 2.8 and 2.11. All Python API tests still pass. This change makes this fixture more like what PyPI hosts, so :+1: to that.

**Comment by Ichimonji10** [comment]
Updated fixtures compiled and made available on repos.fedorapeople.org, and all Python tests run with a set of Pulp 2.8-2.11 systems. All tests passed.

**Pull request merged**
